language: node_js
node_js:
  - 11
script: npm run build
after_script:
  - cp .nojekyll public/
  - cp README.md public/
  - cp LICENSE public/
branches:
  only:
    - master-content
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_url: github.com
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: public
  on:
    branch: master-content
